### ISSUE TITLE
保留文件时间戳

### ISSUE THREAD

**Issue by Summer20130725** [taurusxin/ncmdump#1]
作者大大你好，我用了你这个命令行版本的网易音乐解码器我觉得不错，我想给个建议就是能否保留原始文件时间戳？转码之后文件时间变了！

**Comment by taurusxin** [comment]
没问题，这几天有时间看看

**Comment by Summer20130725** [comment]
> 没问题，这几天有时间看看

作者大大，不用看了我想了一个晚上想出来了。有时间把这几行代码加上去，代码如下：
![1](https://github.com/taurusxin/ncmdump/assets/48155342/867c5a7f-f3a6-4ea7-9d4e-bceb89629e3b)
```C++
/* ncmcrypt.h */

#ifdef UNICODE
#undef UNICODE
#endif
#include <windows.h>

/* only read */
#define O_R 0x000000

/* only write */
#define O_W 0x000001

BOOL WINAPI archivesTime(LPCTSTR filename, bool blMode);
BOOL WINAPI getFileTimeEx(HANDLE hFile, FILETIME ft[3]);
BOOL WINAPI setFileTimeEx(HANDLE hFile, FILETIME ft[3]);
```
![2](https://github.com/taurusxin/ncmdump/assets/48155342/ca4dfc47-51bb-46b6-8b7e-7147b0667828)
![3](https://github.com/taurusxin/ncmdump/assets/48155342/cf5905bf-0f60-42cd-b557-27328e4143db)
```C++
/* ncmcrypt.cpp */

/* Creation, LastWrite, LastAccess */
FILETIME AllFileTime[3] = {0};

BOOL WINAPI NeteaseCrypt::getFileTimeEx(HANDLE hFile, FILETIME ft[3])
{
	DWORD dwRet = FALSE;
	dwRet = GetFileTime(hFile, ft, ft + 2, ft + 1);
	return dwRet;
}
BOOL WINAPI NeteaseCrypt::setFileTimeEx(HANDLE hFile, FILETIME ft[3])
{
	DWORD dwRet = FALSE;
	dwRet = SetFileTime(hFile, ft, ft + 2, ft + 1);
	return dwRet;
}
BOOL WINAPI NeteaseCrypt::archivesTime(LPCTSTR filename, bool blMode)
{
	HANDLE hFile = nullptr;
	DWORD dwRet = FALSE;

	hFile = CreateFile(
		filename,
		blMode == O_W ? FILE_WRITE_ATTRIBUTES : FILE_READ_ATTRIBUTES,
		FILE_SHARE_READ | FILE_SHARE_WRITE,
		NULL,
		OPEN_EXISTING,
		FILE_ATTRIBUTE_NORMAL,
		NULL);

	if (hFile == INVALID_HANDLE_VALUE)
	{
		std::cout << __FUNCTION__ << "() File Handle is Invalid!!!" << std::endl;
		return -1;
	}

	switch (blMode)
	{
	case O_R:
		dwRet = getFileTimeEx(hFile, AllFileTime);
		break;
	case O_W:
		dwRet = setFileTimeEx(hFile, AllFileTime);
		break;
	}

	CloseHandle(hFile);
	return dwRet;
}
```
调用位置：
1.  读取文件时间
     ![4](https://github.com/taurusxin/ncmdump/assets/48155342/0ba91a8b-7270-401c-97f7-45f1e9f02e13)
2.  写入文件时间
    ![5](https://github.com/taurusxin/ncmdump/assets/48155342/0d8bfe9b-bbbd-4c75-83a5-e74f41cd5f39)

效果：
    ![加密文件时间戳](https://github.com/taurusxin/ncmdump/assets/48155342/d0cd2211-d638-490c-9954-1c88aba58eaa)
    ![解密文件时间戳](https://github.com/taurusxin/ncmdump/assets/48155342/0443a3d1-4e95-4c65-afb3-780e412c6819)

**Comment by taurusxin** [comment]
感谢提供代码，有时间进去
