### ISSUE TITLE
[Bug] MSVC版本在处理特殊字符文件名出现问题 

### ISSUE THREAD

**Issue by aquawius** [taurusxin/ncmdump#13]
**Describe the bug**
##### 处理正常的日文字符文件名没有问题.

如图:
![image](https://github.com/taurusxin/ncmdump/assets/70997816/aac4f778-4132-40a6-aa2d-c80f18c2049d)

我将文件名后面的特殊字符删除后, 程序正常转换.

本来是使用-d选项直接处理文件夹, 程序出现异常而中断运行了.

我不知道这个文件名的字在日语文字中是不是属于特殊字符, 我发现在Windows Terminal中会出现光标在文字中间的情况(可能是导致问题的原因 (类似终端的连体字?)).
![image](https://github.com/taurusxin/ncmdump/assets/70997816/cafb5005-a281-4d8d-aac6-ecf3a35df7e5)

![recording](https://github.com/taurusxin/ncmdump/assets/70997816/4961d29c-ff2e-4ead-aa84-4c0985735f87)

**我使用的版本: `Release 1.2.1`**  也就是这个release的MSVC版本
[ncmdump_1.2.1_windows_msvc_amd64.zip] (https://github.com/taurusxin/ncmdump/releases/download/1.2.1/ncmdump_1.2.1_windows_msvc_amd64.zip)

#### English Translate:

**Describe the bug**
The MSVC version has problems handling file names with special characters.
After I delete the special characters after the file name, the program converts normally.

I don't know if the word of this file name is a special character in Japanese text, but I found that in Windows Terminal, the cursor appears in the middle of the text. (may problem)

Version I use: Release 1.2.1 MSVC

**Comment by taurusxin** [comment]
![PixPin_2024-02-19_10-48-13](https://github.com/taurusxin/ncmdump/assets/17809960/9bccf627-2f1c-481e-b819-9a43241d396e)
<img width="865" alt="PixPin_2024-02-19_10-47-43" src="https://github.com/taurusxin/ncmdump/assets/17809960/cb4eca09-5e29-4621-abc5-fa076b89c8d2">
在我这里，使用Release下载的exe似乎没有问题，应该就是你的终端问题，正常来说光标应该是一个字符一个字符来的，但是你这个出现在中间的情况确实不正常，你可以用 `chcp` 看一下终端的代码页吗？

**Comment by taurusxin** [comment]
或者，你可以参考 [这里](https://learn.microsoft.com/zh-cn/troubleshoot/windows-server/system-management-components/powershell-console-characters-garbled-for-cjk-languages) 来试着修复一下，可能也和字体有关

**Comment by aquawius** [comment]
我是用的字体是[Cascadia Code](https://github.com/microsoft/cascadia-code).

倒是发现日语字符还挺有这样的连写字符, 和前面的字符能够形成连写.  (就像有些支持连体的字体 >= 写成一整个符号)
![recording](https://github.com/taurusxin/ncmdump/assets/70997816/37ba72f8-d163-4ad0-8b53-5062345b31b7)

Cascadia Code是这样的:
![image](https://github.com/taurusxin/ncmdump/assets/70997816/cd1dd546-ef70-42e3-9b51-7b8d94cf3bb8)


应该不是代码页的问题.
![image](https://github.com/taurusxin/ncmdump/assets/70997816/56b0c373-db35-43ad-90c6-ca683ea3aed7)

**严格来说倒也不是什么大问题, 不算Bug吧. 改个文件名就好.**
