### ISSUE TITLE
[Bug] 文件夹或文件名中出现符号、部分日文等，会导致转换失败。

### ISSUE THREAD

**Issue by alexblair** [taurusxin/ncmdump#15]
**Describe the bug**
当文件名中包含特殊字符时，会触发转换失败。特殊字符包括 特定得日文、符合、中文等。
具体案例如下：

**原始文件名 转换失败，没有产生文件**
![image](https://github.com/taurusxin/ncmdump/assets/4616320/1550c3d0-4c2a-4b9f-bf71-dcda5d02c914)

**同一个文件 修改文件名后正常**
![image](https://github.com/taurusxin/ncmdump/assets/4616320/c4a7da73-b3b0-4329-82f0-6937f4db94ab)

** 文件名 **
`花澤香菜 - もうそう♥えくすぷれす.ncm`

**Comment by taurusxin** [comment]
你好，请尝试一下 https://github.com/taurusxin/ncmdump/actions/runs/8353671554/job/22865767633 中的构建文件，如果测试成功，我将其上传至 Release

**Comment by alexblair** [comment]
![image](https://github.com/taurusxin/ncmdump/assets/4616320/81f6bdbf-3e4d-4778-ad4d-6759df50fe80)

比较可惜，执行后没有报错信息了，但是转换并没有执行。
我把文件打包到NAS了，您可以下载到本地试试看 （windows）
https://alexblair.synology.me:8885/d/s/xjn52L44f60KcT6GtFSslqQER13bWOmR/l4lUSt5KwOe1DFJYrVCan04XsFVZsi-Q-BLNggH8IOQs

readme.md 里 附带我写的一个本地测试脚本，或许能帮助您快速定位问题。

**Comment by alexblair** [comment]
看了源码（虽然不太懂C ，我写PHP java的），文件路径的判断实际上调用的是系统函数。
搜索了下 可能是这个原因：（供参考,不一定对）
https://blog.csdn.net/gamerzhj/article/details/125692487
如果使用 std::filesystem::u8path  会不会问题得到解决？

**Comment by taurusxin** [comment]
请试一下 MinGW 的版本，在我本地测试通过，msvc的似乎还有问题，先不要尝试。
https://github.com/taurusxin/ncmdump/actions/runs/8370516616

**Comment by taurusxin** [comment]
你好，经测试已经彻底修复了这个问题，用下面的自动构建试一下，没问题就发布 Release。

https://github.com/taurusxin/ncmdump/actions/runs/8385495511

**Comment by alexblair** [comment]
测试通过！
非常感谢！

测试环境 windows server 2022

**Comment by taurusxin** [comment]
> 测试通过！
> 
> 非常感谢！
> 
> 
> 
> 测试环境 windows server 2022 

感谢反馈，这个问题之前开过好几个issue，都是临时解决，这次应该是彻底修好了，全局使用UTF-8适配了所有操作系统语言和字符集。
