### ISSUE TITLE
[Bug] 文件被占用

### ISSUE THREAD

**Issue by sciencekiller** [taurusxin/ncmdump#17]
在使用1.3.1版本的dll时，发现仍有文件被占用的问题。
![图片](https://github.com/taurusxin/ncmdump/assets/119404250/9d92bf92-673c-4e2f-b779-3f495779c52d)
这里已经销毁了实例，但是在Move过程中抛出错误
![图片](https://github.com/taurusxin/ncmdump/assets/119404250/e1f59238-7629-47ec-a445-4f9d6bb7ca8d)
并且在程序运行的状态下在文件夹中删除转换后文件显示被占用
![图片](https://github.com/taurusxin/ncmdump/assets/119404250/fa6b1d68-69fa-42fb-85ee-8a512b20bf3f)

**Comment by taurusxin** [comment]
请测试 Action 构建 https://github.com/taurusxin/ncmdump/actions/runs/8578206006

**Comment by sciencekiller** [comment]
程序可以正常运行，但是出现报错。当文件含有中文名时，抛出SEHException，应该不是C#的问题而是dll的问题
![图片](https://github.com/taurusxin/ncmdump/assets/119404250/0ce36741-0fa4-48d0-821a-8955075d08bf)

**Comment by taurusxin** [comment]
请测试新 Action https://github.com/taurusxin/ncmdump/actions/runs/8578621796 此提交传递 UTF-8 到 DLL，同时请参照新的 Example 示例更新 C#包装类的构造函数 https://github.com/taurusxin/ncmdump/blob/8a13d0fe07319e6349aad89deb65b93f7bbd1394/example/csharp/NeteaseCrypt.cs#L31C1-L40C10
以正确转换编码。

**Comment by sciencekiller** [comment]
感谢，问题已经解决，我会在未来为C#版本添加更多功能（如异步转换）。再次感谢你的无偿贡献。
________________________________
发件人: TaurusXin ***@***.***>
发送时间: 2024年4月6日 12:13
收件人: taurusxin/ncmdump ***@***.***>
抄送: Sciencekill ***@***.***>; Author ***@***.***>
主题: Re: [taurusxin/ncmdump] [Bug] 文件被占用 (Issue #17)


请测试新 Action https://github.com/taurusxin/ncmdump/actions/runs/8578621796 此提交传递 UTF-8 到 DLL，同时请参照新的 Example 示例更新 C#包装类的构造函数 https://github.com/taurusxin/ncmdump/blob/8a13d0fe07319e6349aad89deb65b93f7bbd1394/example/csharp/NeteaseCrypt.cs#L31C1-L40C10
以正确转换编码。

―

**Comment by taurusxin** [comment]
[Release 1.3.2](https://github.com/taurusxin/ncmdump/releases/tag/1.3.2)
