### ISSUE TITLE
macOS 下编译问题

### ISSUE THREAD

**Issue by coanor** [taurusxin/ncmdump#2]
几个问题，我就不 fork PR 了，望仓主补正下 Readme 以及 Makefile：

- MacOS 下 `brew install taglib` 后，并不能直接 make 通过，仍然报告链接错误，修复办法：

 ```shell
$ brew info taglib  # 获取安装后的 lib 路径
 ```

- 需修改 Makfile，并添加头文件路径（直接使用 clone 后的本地 taglib 头文件）

```Makefile
macos:
	clang++ main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag \
		-I taglib/include \
		-L/opt/homebrew/Cellar/taglib/1.13.1/lib/   # 此即上面 info 命令获取的 taglib 路径，视情况而定
	strip ncmdump
```

> 另：release 页面下载的 macOS 平台二进制并不能直接运行，提示动态库找不到。还是建议大家直接编译。

**Comment by taurusxin** [comment]
确认能复现，现在因为新的 Mac 是 Apple Silicon based，所以默认安装的软件包都在 /opt/homebrew 目录下，且动态库的路径不处于环境变量中，所以需要手动指定库的位置或者添加软链接，Release 找不到动态库同理，需要手动添加库目录到环境，新commit 已针对 Apple Silicon 新增编译选项。

手动指定环境目录
```shell
export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib
make macos-arm64
```
