### ISSUE TITLE
怎么指定转换的格式为mp3或flac？

### ISSUE THREAD

**Issue by xinjiajuan** [taurusxin/ncmdump#20]
怎么指定转换的格式为mp3或flac？是否和ncm源文件有关？

**Comment by taurusxin** [comment]
你好，你说的没错，和ncm源文件有关，有些下载下来的音频是mp3，有些无损的则是flac。

代码中的 [这里](https://github.com/taurusxin/ncmdump/blob/0a6ac353ffe08807fc5529db14f4dea3c732411d/src/ncmcrypt.cpp#L282-L293) 是用于判断源文件的格式的。
