### ISSUE TITLE
Exception: Not netease protected file

### ISSUE THREAD

**Issue by kylehz** [taurusxin/ncmdump#23]
转换的时候报错了
Exception: Not netease protected file 'aaa.ncm'

**Comment by kylehz** [comment]
我确实是从网易云上下载的
[陈粒 - 种种.ncm.zip](https://github.com/user-attachments/files/16622577/-.ncm.zip)

**Comment by taurusxin** [comment]
你这个样本已经是flac了，后缀名不对，你下载的是什么版本

![PixPin_2024-08-15_16-14-51](https://github.com/user-attachments/assets/ef25dd94-960b-4ef2-b2fb-fe3d5406539a)

**Comment by taurusxin** [comment]
工具是没问题的，我测试了网易云下载的的各种版本都能正
![2](https://github.com/user-attachments/assets/eced86b3-9228-4dc0-b15c-d067dbc5a9d9)
常解密。

**Comment by kylehz** [comment]
安卓上下载的无损，确实后缀改成flac就可以直接播放了

**Comment by taurusxin** [comment]
安卓的下载可能特殊一点吧，各种格式都以ncm结尾了，没问题的话就先关了。
