### ISSUE TITLE
转换出来的flac是不是有问题,无法正常播放和转换mp3

### ISSUE THREAD

**Issue by xvjialing** [taurusxin/ncmdump#24]
[抓不住旳青春 - 山海皆可平.flac.zip](https://github.com/user-attachments/files/16637314/-.flac.zip)

**Comment by taurusxin** [comment]
源文件有吗？另外请按照 Issue 模版进行提问。

**Comment by taurusxin** [comment]
未回复，close 处理

**Comment by neverhoodboy** [comment]
网易云音乐升级到 3.0 后会有这个问题
[Uploading 加古隆 - 主题歌“アメイジング・グレイス”.ncm.zip…]()

**Comment by taurusxin** [comment]
> 网易云音乐升级到 3.0 后会有这个问题 [加古隆 - 主题歌“アメイジング・グレイス”.ncm.zip](https://github.com/user-attachments/files/16739423/-.ncm.zip)

已确认有问题，麻烦请开一个新 issue，在那边跟进。

**Comment by neverhoodboy** [comment]
> > 网易云音乐升级到 3.0 后会有这个问题 [加古隆 - 主题歌“アメイジング・グレイス”.ncm.zip](https://github.com/user-attachments/files/16739423/-.ncm.zip)
> 
> 已确认有问题，麻烦请开一个新 issue，在那边跟进。

已提交: https://github.com/taurusxin/ncmdump/issues/26
