### ISSUE TITLE
[Bug] 网易云音乐 mac 客户端升级到 3.0 后所下载的 ncm 文件通过 ncmdump 转换成 flac 后无法播放

### ISSUE THREAD

**Issue by neverhoodboy** [taurusxin/ncmdump#26]
**Bug 描述**
网易云音乐 mac 客户端升级到 3.0 后所下载的 ncm 文件通过 ncmdump 转换成 flac 后无法播放。2.x 版本的 mac 端所下载的 ncm 文件没问题。

**复现方法**

把网易云音乐 mac 客户端升级到 3.0.1 (2184)，下载一个 ncm 文件，用 ncmdump 转换成 flac 文件，尝试播放即可复现。
PS: 执行 ncmdump 时有一个警告: missing album can't fix album image!

**预期行为**

用 ncmdump 转换得到 flac 文件应当能正常播放。

**屏幕截图**

无

**环境**

- OS: [macOS 14.6.1]
- 软件版本: [ncmdump 1.3.2, 网易云音乐 mac 端 3.0.1 (2184)]

**附加内容**

样例 ncm 文件: 
[加古隆 - 主题歌“アメイジング・グレイス”.ncm.zip](https://github.com/user-attachments/files/16748182/-.ncm.zip)

**Comment by taurusxin** [comment]
请问下载的音质是什么？

**Comment by neverhoodboy** [comment]
> 请问下载的音质是什么？

上面附的那个样例 ncm 文件，在 https://ncm.worthsee.com/ 上转成 flac 后（能正常播放），比特率是 664 kbit/s

**Comment by duskmizzle** [comment]
升级客户端3.x以后就不能正常转换了，音质高清臻音

**Comment by ahuang0808** [comment]
更新客户端后尝试下载各种音质，似乎都不能播放了

**Comment by luxuxl** [comment]
我也遇到了此问题, 我本来以为是我播放器的原因
