### ISSUE TITLE
[Bug] 网易云音乐 mac 客户端升级到 3.0 后下载的 ncm 文件通过 ncmdump 转换后丢失封面图

### ISSUE THREAD

**Issue by neverhoodboy** [taurusxin/ncmdump#29]
**Bug 描述**
网易云音乐 mac 客户端升级到 3.0 后下载的 ncm 文件通过 ncmdump 转换后丢失封面图（mp3 格式和 flac 格式都会丢失）。

**复现方法**

把网易云音乐 mac 客户端升级到 3.0.4 (2237)，下载一个 ncm 文件，用 ncmdump 转换成 mp3/flac 文件，用 mp3tag 等软件查看文件的元信息，可以看到没有封面图。（对比，同样的 ncm 文件，在 https://ncm.worthsee.com/ 上转换格式，产生的 mp3/flac 文件是有封面图的。）

PS: 执行 ncmdump 时有一个警告: missing album can't fix album image!

**预期行为**

用 ncmdump 转换得到的 mp3/flac 文件应有封面图。

**屏幕截图**

无

**环境**

- OS: [macOS 15.0]
- 软件版本: [ncmdump 1.4.0, 网易云音乐 mac 端 3.0.4 (2237)]

**附加内容**

样例 ncm 文件（2 个文件分别会被转换为 mp3 和 flac 格式，ncn 文件本身是有封面图的，可以通过在 https://ncm.worthsee.com/ 上转换来验证）: 

[Paul Russell,Meghan Trainor - Slippin'.ncm.zip](https://github.com/user-attachments/files/17096539/Paul.Russell.Meghan.Trainor.-.Slippin.ncm.zip)
[加古隆 - 主题歌“アメイジング・グレイス”.ncm.zip](https://github.com/user-attachments/files/16748182/-.ncm.zip)

**Comment by taurusxin** [comment]
1.4更新后忘记在README里加了，3.0之后下载的ncm不再内嵌封面图，需要从网络获取，这部分feature已经在开发中。

**Comment by neverhoodboy** [comment]
> 1.4更新后忘记在README里加了，3.0之后下载的ncm不再内嵌封面图，需要从网络获取，这部分feature已经在开发中。

但是为什么同样的 ncm 文件在 https://ncm.worthsee.com/ 上转换后是有封面图的，难道它是另外通过网络去匹配/获取歌曲元数据的？😂

**Comment by taurusxin** [comment]
是的，如果你打开F12会发现，当你上传一个文件时会有一个获取封面图的请求

**Comment by taurusxin** [comment]
> > 是的，如果你打开F12会发现，当你上传一个文件时会有一个获取封面图的请求
> 
> 明白了，实测了一下确实如此，谢谢解答。

不客气，如果有需求的话，我的另一个仓库，完全基于 Golang 重写的版本（https://git.taurusxin.com/taurusxin/ncmdump-go），可以试一下， 支持从网络获取封面图并嵌入，由于可能涉及DMCA，故没有托管在 GitHub

**Comment by neverhoodboy** [comment]
> > > 是的，如果你打开F12会发现，当你上传一个文件时会有一个获取封面图的请求
> > 
> > 
> > 明白了，实测了一下确实如此，谢谢解答。
> 
> 不客气，如果有需求的话，我的另一个仓库，完全基于 Golang 重写的版本（https://git.taurusxin.com/taurusxin/ncmdump-go ），可以试一下， 支持从网络获取封面图并嵌入，由于可能涉及DMCA，故没有托管在 GitHub

看上去很不错，谢谢～
