### ISSUE TITLE
文件名称中带有西语或特殊符号时反序列出错

### ISSUE THREAD

**Issue by gnayhz** [taurusxin/ncmdump#3]
严格意义上不算错误, 可以通过修改文件名为正常名称后再次处理

异常信息:
Exception: not netease protected file

示例文件名(只列举了同类中一个, 仅供参考)
特殊符号( 此处为・)
荻野目洋子 - ダンシング・ヒーロー (Eat You Up).ncm

韩语
단비 - 니가 내리던 하루.ncm

西语
Schnuffel - Häschenparty (Album Version).ncm
Shawn Mendes,Camila Cabello - Señorita.ncm

**Comment by taurusxin** [comment]
目前测试了似乎只在 Windows 上复现，推测可能是 Windows 的文件名编码导致的，有时间修一下。
