### ISSUE TITLE
[Bug] undefined reference to win32_utf8argv

### ISSUE THREAD

**Issue by hu-ximing** [taurusxin/ncmdump#30]
**Bug 描述**

Windows msys 编译提示 `undefined reference to win32_utf8argv(int*, char***)`

**复现方法**

1. CMake 配置项目
  ```shell
  cmake -DCMAKE_BUILD_TYPE=Release -B build
  ```
2. 编译项目
  ```shell
  cmake --build build -j 8
  ```
3. 发生报错

**预期行为**

编译成功

**屏幕截图**

![image](https://github.com/user-attachments/assets/86fc40c0-576e-40b2-b60d-2b0ec1e8e9b3)

**环境**

- OS: Windows 11 MSYS UCRT
- 软件版本: 1.5.0

**附加内容**

`main.cpp` 中注释掉 52-54 行，编译可以成功
```cpp
#if defined(_WIN32)
    win32_utf8argv(&argc, &argv); // Convert command line arguments to UTF-8 under Windows
#endif
```

**Comment by taurusxin** [comment]
配置时是否缺少构建套件，麻烦请删掉 build 目录再试一次
```shell
cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -B build
```
