### ISSUE TITLE
[Bug] *For ncmdump-go* foobar2000 reports "Unsupported format or corrupted file"

### ISSUE THREAD

**Issue by mooesy** [taurusxin/ncmdump#32]
**Bug 描述**

This issue is for ncmdump-go. I posted it here since I couldn't register an account for the repo where it belongs. 

foobar2000 reports "Unable to open item for playback (Unsupported format or corrupted file)" when importing NCM songs unlocked with this tool. When tested with foobar2000's integrity verification tool it shows the following:

`Error: Corrupted FLAC stream`
`Error: Unsupported format or corrupted file`

**复现方法**

复现此 Bug 的方法

1. unlock NCM songs with ncmdump-go
2. import the songs into foobar2000
3. 发生报错

**预期行为**
foobar2000 shouldn't be showing any errors.

**屏幕截图**

![image](https://github.com/user-attachments/assets/84d6bb35-3808-41de-8b7d-a138954acacd)

![image](https://github.com/user-attachments/assets/c08ab93c-c9a1-468b-abab-eae94c187ba7)

**环境**

- OS: Windows 11
- 软件版本: 1.6.0, vanilla foobar2000 v2.24

**附加内容**

添加更多其他内容以帮助开发者更好地了解这个 Bug。

**Comment by taurusxin** [comment]
请提供源文件样本以供分析

**Comment by mooesy** [comment]
[sample.zip](https://github.com/user-attachments/files/17449672/sample.zip)

Integrity verification report included

**Comment by taurusxin** [comment]
Using Chrome, ffplay, and MPC players can open, decodate and play the file normally, please try different software.

**Comment by taurusxin** [comment]
It seems to be an issue with ncmdump-go. Please wait for me to locate and fix the bug.

**Comment by taurusxin** [comment]
This is caused by the metadata lib `go-flac`, I'm currently woking on it and contacting with the author of it.

**Comment by taurusxin** [comment]
It seems that NetEase Cloud Music 3.0.5 has started to embed metadata with album cover images in music files again. Maybe you can try using the C++ version. I tested several files and did not encounter the problem of missing cover images.

**Comment by taurusxin** [comment]
Fixed

See Release 1.7.0: https://git.taurusxin.com/taurusxin/ncmdump-go/releases/tag/1.7.0
