### ISSUE TITLE
[Bug] 10月25日刚发布的新歌，使用2.7.1版本下载的，提示ERROR

### ISSUE THREAD

**Issue by punkhuoye** [taurusxin/ncmdump#35]
**Bug 描述**
10月25日刚发布的新歌，使用2.7.1版本下载的，转换时，提示ERROR
ncmdump Passion.ncm
[Info] Processing 'Passion.ncm'
[Error] Reading 'Passion.ncm' failed: not a ncm file
[Error] Failed to process file 'Passion.ncm

**复现方法**
复现此 Bug 的方法

1. 打开(http://music.163.com/song?id=2639024679&userid=3365566)(http://music.163.com/song?id=2639012545&userid=3365566)这两首歌
2. 无论是拖动进入ncmdump，还是用命令行，都会提示[Error] Reading 'Passion.ncm' failed: not a ncm file
4. 发生报错

**预期行为**

解释一下原本应该出现的结果。

**屏幕截图**
这里为错误输出
![微信截图_20241029012558](https://github.com/user-attachments/assets/e0cb1425-33c0-4185-8597-9eb61c179076)

这里是其他下载的歌曲可以正常转换
![微信截图_20241029012746](https://github.com/user-attachments/assets/bcbbaa76-ae49-4d46-82d1-f1bab686b086)

**环境**

- OS: [win10]
- 软件版本: [1.5]

**附加内容**

**Comment by taurusxin** [comment]
看命令行输出这似乎不是本项目，请到正确的仓库提Issue

**Comment by taurusxin** [comment]
![PixPin_2024-10-29_07-37-20](https://github.com/user-attachments/assets/fa20dca1-433a-4402-b79f-c3ea32559ef0)
使用本项目的 ncmdump，可以正确处理。

**Comment by punkhuoye** [comment]
大佬来反馈了，之前使用的网易云是2.7.1，最新下载的歌曲会提示这个问题，升级wyy到3.0.3，下载的高清臻音可以转换了。

**Comment by taurusxin** [comment]
你的截图上输出提示不是这个项目
