### ISSUE TITLE
[Bug] 无法转换ncm

### ISSUE THREAD

**Issue by operav** [taurusxin/ncmdump#36]
**Bug 描述**

无法转换ncm，无论是直接把ncm往ncmdump.exe上拖，还是打开cmd转换

**复现方法**

1. 直接把ncm文件往ncmdump.exe拖，闪了一下，就结束了，什么也没发生
2. 打开cmd，把ncmdump.exe拖上去，打个空格，把音乐文件拖上去，按下键盘回车
cmd则显示[1m[31m[Exception] [0m[31mNot netease protected file

**预期行为**

以前直接转换成mp3

**屏幕截图**

![1](https://github.com/user-attachments/assets/4ef02cc5-96a1-4458-8beb-a1741250737a)

**环境**

- OS: [e.g. Windows 11]
- ncmdump版本：1.5.0
- 网易云音乐软件版本：2.10.13
- 音质选择：极高

**附加内容**
音乐文件链接
https://music.163.com/song?id=2620442140
https://music.163.com/song?id=2629021154

也可能是我操作问题，还请大佬指教，感谢

**Comment by taurusxin** [comment]
附件提供一下 ncm 文件，我看下

**Comment by taurusxin** [comment]
> [Desktop.zip](https://github.com/user-attachments/files/17552020/Desktop.zip)

404了，再传下，或者直接发送到我的邮箱 i@taurusxin.com

**Comment by taurusxin** [comment]
> > 从文件头来看，已经是mp3文件了，直接改后缀即可，实测可以正常播放。
> > 至于为什么后缀还是ncm，估计是网易的Bug吧，之后我加入个文件识别，发现已经是mp3/flac直接给出提示。
> > ![](https://private-user-images.githubusercontent.com/17809960/380990419-f6043f52-8ea0-4431-9078-d37c3c982e5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODA3NDcsIm5iZiI6MTczMDE4MDQ0NywicGF0aCI6Ii8xNzgwOTk2MC8zODA5OTA0MTktZjYwNDNmNTItOGVhMC00NDMxLTkwNzgtZDM3YzNjOTgyZTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA1NDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMmRkZDFiOGRiM2VhY2M3ODMzYjgxYTczODFkNTQ4MzEwY2JhZDY1MTM3MDk4YmNmNzFhYzNkZWQ0YjExYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W5fLJL2ITfH_wJkSa9ow25OF4w0ENpznpiinEqutgjw)
> 
> 。。。。。。不愧是网易云。。。😂😂😂 电脑新版狂吃系统资源，手机安卓端新版也狂吃运行内存，现在还整了个这个操作吓唬人😂😂😂 谢谢大佬了

不客气~
