### ISSUE TITLE
[Bug] ncmdump-go 转换后元数据损坏/不合法

### ISSUE THREAD

**Issue by justinLia** [taurusxin/ncmdump#37]
**Bug 描述**

由于ncmdump-go（git.taurusxin.com）无法创建新用户开issue，我只好在这里开啦。

ncmdump-go将ncm转换成flac文件后，元数据无法读取。

**复现方法**

下载一首ncm音乐，使用ncmdump-go转换，查看其元数据。

**环境**

- 操作系统: macOS 
- 网易云版本（重要）: [2.3.18]
- 所选择的音质: 无损

**Comment by taurusxin** [comment]
可以上传一下样本吗？由于目前 Golang 下没有对 flac 元数据处理有较好支持的库，后面考虑重写。

**Comment by taurusxin** [comment]
另外是用什么工具查看的元数据？

**Comment by taurusxin** [comment]
![3](https://github.com/user-attachments/assets/f66ab44b-8dac-409e-aafd-76e1d7cea070)
![2](https://github.com/user-attachments/assets/225d906f-d188-4b71-9682-b6d228cbc406)
![1](https://github.com/user-attachments/assets/18538031-bb3f-42f7-9f65-37f45523d1bc)
我这里不管是用 MPC 播放器，Windows资源管理器的图标显示，以及 MediaInfo 都能正确显示元数据或者是图片，不知道你的工具是否有问题，目前在我这里测试均正常，

**Comment by taurusxin** [comment]
你用的ncmdump-go是什么版本

**Comment by taurusxin** [comment]
> > 你用的ncmdump-go是什么版本
> 
> 就是这个：https://git.taurusxin.com/taurusxin/ncmdump-go 前几天下的

是1.7.0吗，我测试没问题，你用最新版再试试看

**Comment by mrliaocn** [comment]
MAC M3芯片 App版本3.0.5 (2263) ncmdump命令执行后无法播放

**Comment by taurusxin** [comment]
> MAC M3芯片 App版本3.0.5 (2263) ncmdump命令执行后无法播放

请开新 Issue，并提供样本

**Comment by taurusxin** [comment]
> > > 你用的ncmdump-go是什么版本
> > 
> > 
> > 就是这个：https://git.taurusxin.com/taurusxin/ncmdump-go 前几天下的
> 
> 是1.7.0吗，我测试没问题，你用最新版再试试看

暂无回复的话就先关闭了。
