### ISSUE TITLE
[Bug] Windows环境下无法转换

### ISSUE THREAD

**Issue by rsmovingddd** [taurusxin/ncmdump#38]
**Bug 描述**

下载下来的ncm文件无法转换，报错中含有乱码

**复现方法**

复现此 Bug 的方法

1. 下载Release 1.5.0 的msys2或者msvc版（自己在本地也编译了一次msvc版本）
2. 下载任意一首SQ的ncm文件
3. 使用Powershell或者cmd转换，转换失败，报错含有乱码

![微信截图_20241031154657](https://github.com/user-attachments/assets/d484d6fa-b66c-41b0-ac81-7778917d191e)

```powershell
C:\Users\zrs\Downloads\ncmdump-1.5.0-windows-amd64-msys2>ncmdump "ASCA - 雲雀.ncm"
[1m[31m[Exception] [0m[31mNot netease protected file[0m 'ASCA - 雲雀.ncm'
``` 

**环境**

- 操作系统: Windows 10 22H2
- 网易云版本（重要）: 2.10.10
- 所选择的音质: SQ

**Comment by Teiii14** [comment]
前几天是正常的，今天一试发现转换不了了，不知道是不是网易云加密了

**Comment by taurusxin** [comment]
乱码是因为你用的cmd，我输出的文字带有彩色字体。

样本传一下，不然没法分析啊

**Comment by taurusxin** [comment]
提示 Not netease protected file 大概率是该文件已经是 mp3 或者 flac，并非网易的加密格式，自行改个后缀即可

**Comment by rsmovingddd** [comment]
> 提示 Not netease protected file 大概率是该文件已经是 mp3 或者 flac，并非网易的加密格式，自行改个后缀即可

问题解决，感谢
