### ISSUE TITLE
[Bug] Go开发方式嵌入封面时报错 'encoding: rune not supported by encoding.'

### ISSUE THREAD

**Issue by jwslh** [taurusxin/ncmdump#42]
**Bug 描述**

MP3 转化没什么问题，在嵌入封面时都出现了错误。

**复现方法**

复现此 Bug 的方法

1. 使用本项目处理文件 '...'
2. 发生报错

**屏幕截图**

![屏幕截图 2024-11-08 142134](https://github.com/user-attachments/assets/de193944-1478-40f4-8192-0ea6fef5cdcf)

**环境**

- 操作系统: Windows
- 网易云版本（重要）: 3.0.4(64位)（build: 203152）
- 所选择的音质: 极高

**附加内容**

如果遇到无法转换的问题，请将样本附加到这里，便于分析。

**Comment by taurusxin** [comment]
麻烦传一个样本文件，便于分析。

**Comment by jwslh** [comment]
[Uploading By2 - 我知道.zip…]()

**Comment by taurusxin** [comment]
> Uploading By2 - 我知道.zip…

没传完，重新传一下

**Comment by jwslh** [comment]
[By2 - 我知道.zip](https://github.com/user-attachments/files/17674502/By2.-.zip)

**Comment by taurusxin** [comment]
Fixed.

See [Release 1.7.1](https://git.taurusxin.com/taurusxin/ncmdump-go/releases/tag/1.7.1)
